Integration of Onyx Protocol Token (XCN)
rango-exchange/token-list pull request #1
Opened 2023-10-07 12:40 UTC by MerdyNumber1

Supported blockchains for XCN: Ethereum, BSC.
Native XCN bridge for swapping between Ethereum and BSC: bridge.onyx.org

2023-10-08 05:56 UTC, RanGojo commented
Thanks for the PR @MerdyNumber1 . We will check it soon.

2023-10-08 06:01 UTC, al-onyxprotocol requested changes

2023-10-08 06:01 UTC, al-onyxprotocol commented on tokens/custom/xcn/manifest.json
> +    "name": "Onyx Protocol Token",
```suggestion
    "name": "Onyxcoin",
```

2023-10-08 06:01 UTC, al-onyxprotocol commented on tokens/custom/xcn/manifest.json
> +    "name": "Onyx Protocol Token",
```suggestion
    "name": "Onyxcoin",
```

2023-10-08 07:54 UTC, al-onyxprotocol commented
DEXes:

Ethereum:
[UniSwap v2 XCN/ETH](https://v2.info.uniswap.org/pair/0x859f7092f56c43bb48bb46de7119d9c799716cdf)
[UniSwap v3 XCN/ETH](https://info.uniswap.org/#/pools/0x5c7f114086ac472162b66b259eac89e820974461)

BNB Smart Chain:
[PancakeSwap v3 XCN/WBNB](https://pancakeswap.finance/info/v3/pairs/0xa694a7c24a84ec66db840caa745fce8413bde0d8)
[PancakeSwap v3 XCN/USDT](https://pancakeswap.finance/info/v3/pairs/0x1aaecb940a342d89258a297e2418b22ce1bf5d5e)
[AmpleSwap XCN/USDT](https://ampleswap.com/swap?outputCurrency=0x7324c7c0d95cebc73eea7e85cbaac0dbdf88a05b&inputCurrency=0x55d398326f99059fF775485246999027B3197955)

2023-10-08 15:31 UTC, al-onyxprotocol approved these changes

2023-10-11 08:40 UTC, RanGojo commented
@MerdyNumber1 @al-onyxprotocol Thanks for the PR.
Your token will be updated in our production env in the next release during the next week.

2023-10-11 08:40 UTC, merged